// import morgan from "images/morgan.png";
import musk from "images/musk.png";
// import albert from "images/albert.png";
import avatar1 from "images/avatar/01.png";
import avatar2 from "images/avatar/02.png";
import avatar3 from "images/avatar/03.png";
import avatar4 from "images/avatar/04.png";
import avatar5 from "images/avatar/05.png";
import avatar6 from "images/avatar/06.png";
import avatar7 from "images/avatar/07.png";
import avatar8 from "images/avatar/08.png";
import avatar9 from "images/avatar/09.png";
import avatar10 from "images/avatar/10.png";
import avatar11 from "images/avatar/11.png";
import avatar12 from "images/avatar/12.png";
